#!/bin/bash

set -ex

STACK=$1

if [ $STACK != "cflinuxfs2" ] && [ $STACK != "lucid64" ]; then
  echo "${STACK} is not a valid stack!"
  exit 1
fi

create_receipt() {
  echo "Rootfs SHASUM: `shasum $STACK/rootfs.tgz`" > $STACK/${STACK}_receipt
  echo "Docker Image: `docker images | grep cloudfoundry/$STACK | grep latest | awk '{ print $3 }'`" >> $STACK/${STACK}_receipt
  echo "S3 ETag: `cat etag`" >> $STACK/${STACK}_receipt
  echo "" >> $STACK/${STACK}_receipt
  cat $STACK/$STACK_dpkg_l.out >> $STACK/${STACK}_receipt
}


cleanup() {
  rm etag
  rm $STACK/rootfs.tgz
  echo "Don't forget to save the $STACK/${STACK}_receipt file"
}

./upload_to_s3 $STACK > etag
./docker_push.sh $STACK
create_receipt
cleanup
